id: PEAE1D108
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: es
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    a5a759ef32074523959bc48b496dd224:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    23d5c10d92d44a7fa95d250b1c1493df:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    c6697c56e513494281492058e2fcb15e:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    dcfccbb78e754fed99946598500887f4:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    190d9369dda04e578ff3e79823010b43:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    8a9a20a49c5a4e738f53382fc03b68f8:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    980455934e7544968d8318a2e65b8a48:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    590bcb86b2f24f2f9fe046995e8cd0b2:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    1de5cb18eb19404f8b1c61294f3765bd:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    c21b94cdfa334945945547415e7f46c1:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    8b085e72c7bb4cc9ab9ebb573da35a4e:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    910ee7752e844cf29b6eeef4ba54ce2f:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.691006'
last_modified_at: '2022-02-28T23:00:39.691009'
